# Generated by Django 3.0.5 on 2022-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Uploadfile',
        ),
    ]
