# Generated by Django 3.0.5 on 2022-05-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20220524_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.FileField(upload_to='media/'),
        ),
    ]
