# Generated by Django 3.0.5 on 2022-05-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_auto_20220525_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
